### ISSUE TITLE
Pushpin retry connections indefinitely

### ISSUE THREAD

**Issue by mitalkakaiya** [fanout/pushpin#47653]
Hi,

We are considering to run background job for the incoming request, and assign unique id (e.g. channel id) for each incoming request, and Pushpin could send responses to those channels via background tasks.

Unfortunately, Pushpin retries incoming requests indefinitely.

Noticed the similar Github issue #47646, but not sure how does the application set "Grip-Last" value for large numbers of concurrent requests, and each request has random request id? 

Just reproduce this behaviour in sample gist code - Go Lang/Dockerfile as follow:

> https://gist.github.com/mitalkakaiya/2650e995f00d9b1574be6017ab9d4663

Please feel free to advise alternatives to resolve it, or gist updates would be helpful. 

Regards,
Mital

**Comment by mitalkakaiya** [comment]
Thanks for your quick response, and explained Pushpin workflow about `Grip-Last` header. Updated Pushpin source code locally, and works as expected.

As per the above comment, Pushpin makes an initial request to the server as per point 2, and makes an another request to the server as per point 4. Just wondering about the following queries:

1. What would be the reason for Pushpin to make 2nd request the server? 

2. What is recommended option to execute request in the backend? Should backend (e.g. generate pdf) run on the first request or second request?

3. If there are multiple backends connected (e.g. backend1, backend2, backend3 etc), does pushpin send the second request to the same backend server as the first request? Just wondering if there is any internal workflow about it.

4. Please feel free to advise me if there is any documentation or blog post to explain some of these internal workflow details.

Thanks again, and looking forward to understand more details about Pushpin.

Regards,
Mital

**Comment by jkarneges** [comment]
1. The second request is an aspect of Pushpin's reliability feature. Pushpin can optionally notify the backend (currently over ZeroMQ) whenever a channel has at least one subscriber, useful for allowing the backend to limit publishing to only Pushpin instances that have subscribers. However, if the need for the backend to publish happens during the moment after Pushpin has gained a subscriber but before the backend has received the subscription event, there's a chance the backend may discard the publish. To work around this, Pushpin will re-issue any requests held in `response` mode shortly after a channel gains its first subscriber, so that clients can quickly pick up any missed data. If you aren't tracking subscriptions, then you don't really need to worry about this, other than be aware you may need to handle retried requests sometimes.

2. The first, since it's best not to rely on the second request always happening (in your case with random channels it should always happen, but for most apps using non-random channels it will vary depending on whether the client is the first subscriber or not; also in the future we might change the conditions or timing of the second request). If you receive a second request, it should return the results of the earlier started task, or hold if the task isn't finished yet.

3. Pushpin does not attempt to send subsequent requests to the same backend. If you have a DNS A record with multiple IP addresses, a different IP might get used for each request. If you have a load balancer between Pushpin and your backends, then the decision is up to your load balancer.

4. http://pushpin.org/docs/advanced/#reliability discusses Pushpin's reliability feature and `Grip-Last`. It was missing some details mentioned here so I've updated it.

**Comment by jkarneges** [comment]
One other thing: when setting up a subscription with a `prev-id`, you need to publish with a `prev-id` as well, otherwise Pushpin will retry the request rather than deliver the message.

**Comment by SpecLad** [comment]
Hello,

I was trying to use Pushpin in the same way as OP, and I hit the same problem. While the workaround in this issue works, may I suggest that Pushpin offer a way to opt out of the reliability protocol entirely? It isn't needed in this use case, so instead of working around it, it would be nice to be able to disable it.

**Comment by jkarneges** [comment]
I'm looking at making this behavior optional: #48218
