### ISSUE TITLE
messages filter

### ISSUE THREAD

**Issue by clyquan** [fanout/pushpin#47666]
According to https://pushpin.org/docs/advanced/#message-filtering, I publish a message below:
`
{
  "items": [
    {
      "channel": "twtpub",
      "meta": {
      	"require_sub": ["123456"]
      },
      "id": "3c552014-57a3-c-ddqqqdqadb26dd1dd11-d9s14",
      "formats": {
        "ws-message": {
          "content": "9x3"
        }
      }
    }
  ]
}
`
However, I got an error: Invalid format: 'meta' contains 'require_sub' with wrong type.

Then I change the `require_sub` to string instead of a list, and it published,  the client who didn't subscribe this channel `123456` got this message, It seems that this parameter `require_sub` doesn't work.

**Comment by jkarneges** [comment]
Hi,

You need to apply the `require-sub` filter to the subscription in order for the `require_sub` meta value to have any effect. For example, responding with a header like:

```http
Grip-Channel: foo; filter=require-sub
```

This is needed because the filter is the thing that actually performs the drop, and has knowledge of potential meta values.

**Comment by clyquan** [comment]
@jkarneges  thanks, I missed this config.
